
[jenkins]
numExecutors = 4

[jenkins.authorizationStrategy.loggedInUsersCanDoAnything]
allowAnonymousRead = true

[jenkins.markupFormatter.rawHtml]
disableSyntaxHighlighting = false

[[jenkins.nodes]]
[jenkins.nodes.permanent]
launcher = "inbound"
mode = "EXCLUSIVE"
name = "lenovo-x1"
remoteFS = "/var/lib/jenkins/agents/lenovo-x1"
retentionStrategy = "always"

[[jenkins.nodes]]
[jenkins.nodes.permanent]
launcher = "inbound"
mode = "EXCLUSIVE"
name = "nuc"
remoteFS = "/var/lib/jenkins/agents/nuc"
retentionStrategy = "always"

[[jenkins.nodes]]
[jenkins.nodes.permanent]
launcher = "inbound"
mode = "EXCLUSIVE"
name = "orin-agx"
remoteFS = "/var/lib/jenkins/agents/orin-agx"
retentionStrategy = "always"

[[jenkins.nodes]]
[jenkins.nodes.permanent]
launcher = "inbound"
mode = "EXCLUSIVE"
name = "orin-nx"
remoteFS = "/var/lib/jenkins/agents/orin-nx"
retentionStrategy = "always"

[[jenkins.nodes]]
[jenkins.nodes.permanent]
launcher = "inbound"
mode = "EXCLUSIVE"
name = "riscv"
remoteFS = "/var/lib/jenkins/agents/riscv"
retentionStrategy = "always"

[appearance.pipelineGraphView]
showGraphOnBuildPage = true

[unclassified.location]
url = "${file:/var/lib/jenkins-casc/url}"

[unclassified.timestamper]
allPipelines = true

[[unclassified.lockableResourcesManager.declaredResources]]
name = "evaluator"
description = "Nix evaluator lock"
