# SPDX-FileCopyrightText: 2022-2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

name: GitHub Actions Version Updater
on:
  workflow_dispatch:
  schedule:
    # Automatically run on every Sunday at 00:00 UTC.
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}
      
      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@64be81ba69383f81f2be476703ea6570c4c8686e # v0.8.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}
          pull_request_title: "Update GitHub Actions to Latest Version"